name: Publish Docker
on: 
  push: 
    paths: 
      - 'r-dsci-100-grading/Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get release version
      id: get_version
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ubcdsci/r-dsci-100-grading
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: r-dsci-100-grading
        tags: "latest,${{ env.RELEASE_VERSION }}"
