name: Publish Docker
on: 
  push: 
    paths: 
      - 'r-dsci-100/Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ubcdsci/r-dsci-100
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: r-dsci-100
        tags: "latest,${{ env.RELEASE_VERSION }}"
